image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: "latest"

portMappings:
  - protocol: tcp
    containerPort: 80
    hostPort: 80

containerName: hello-world-app1

requiresCompatibilities:
  - FARGATE

limits:
  task: 
    memory: 9216
    cpu: 4096
  container:
    memory: 4096
    cpu: 2048
    ulimit: 1024000

executionRoleArn: arn:aws:iam::***:role/ecsTaskExecutionRole

aws:
  region: eu-central-1

logConfiguration:
  options:
    awslogs-group: ecs/hello-world-app1
